-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- TODO: categorize in two: Fixing existing shortcuts vs adding new

-- TODO: These are captured by kitty for window resizing
-- Do something about it
-- map("n", "<S-Up>", ":resize -2<CR>")
-- map("n", "<S-Down>", ":resize +2<CR>")
-- map("n", "<S-Left>", ":vertical resize -2<CR>")
-- map("n", "<S-Right>", ":vertical resize +2<CR>")

-- TODO: explore
-- Map("n", "<TAB>", ":bn<CR>")
-- Map("n", "<S-TAB>", ":bp<CR>")

-- NOTE: It appears it is no longer needed. Explore
-- add an "actual" indent (with spaces/tabs) instead of just
-- putting a cursor there (and thus unindenting the line when the
-- moves away)
-- map("i", "<CR>", "<CR> <BS>")

-- BUILT INTO LAZY VIM
-- Highlight when yanking (copying) text
--  Try it with `yap` in normal mode
--  See `:help vim.highlight.on_yank()`
-- vim.api.nvim_create_autocmd('TextYankPost', {
--   desc = 'Highlight when yanking (copying) text',
--   group = vim.api.nvim_create_augroup('kickstart-highlight-yank', { clear = true }),
--   callback = function()
--     vim.highlight.on_yank()
--   end,
-- })

local map = vim.keymap.set

-- Using https://github.com/knubie/vim-kitty-navigator to integrate
-- vim and kitty splits using the same shortcut key
--
-- Move to window using the <ctrl> hjkl keys
map("n", "<C-h>", "<cmd>KittyNavigateLeft<CR>", { desc = "Go to Left Window" })
map("n", "<C-j>", "<cmd>KittyNavigateDown<CR>", { desc = "Go to Lower Window" })
map("n", "<C-k>", "<cmd>KittyNavigateUp<CR>", { desc = "Go to Upper Window" })
map("n", "<C-l>", "<cmd>KittyNavigateRight<CR>", { desc = "Go to Right Window" })

-- Resize window using Ctrl+Shift+hjkl
map("n", "<C-S-h>", "<cmd>vertical resize -2<CR>", { desc = "Decrease window width" })
map("n", "<C-S-l>", "<cmd>vertical resize +2<CR>", { desc = "Increase window width" })
map("n", "<C-S-j>", "<cmd>resize +2<CR>", { desc = "Increase window height" })
map("n", "<C-S-k>", "<cmd>resize -2<CR>", { desc = "Decrease window height" })

-- Make x and c operations not modify clipboards
map({ "n", "x" }, "x", '"_x')
map({ "n", "x" }, "X", '"_X')
map({ "n", "x" }, "c", '"_c')
map({ "n", "x" }, "C", '"_C')

-- I dont want fancy combinations with > and <
-- Just want to use them to indent/deindent
map("n", "<", "<<")
map("n", ">", ">>")

-- Make > and < work in visual mode as well
map("x", ">", ">gv")
map("x", "<", "<gv")

-- Make o/O come back to normal mode after creating a
-- blank line below/above
map("n", "o", "o <BS><Esc>")
map("n", "O", "O <BS><Esc>")

-- Scroll up/down half a page and put the cursor in
-- the middle
--
-- <C-u>/<C-d>: move half page up/down
-- zz: Recenter so that the line of the cursor is in the middle
-- 0: move the cursor to the start of the line
map({ "n", "x" }, "{", "<C-u>zz0")
map({ "n", "x" }, "}", "<C-d>zz0")

-- In visual mode if you select something and press p, it will paste
-- whatever was in the register, overrwitting the selected text. This
-- is okay, but the overritten text is now placed in that register.
-- This basically limits you to be able to paste only once.
--
-- This keymap makes is so that the register is preserved when pasting
-- over some selected text in visual mode
map("x", "p", function()
  -- Get the current active register...
  local register = vim.v.register
  -- and its contents
  local contents = vim.fn.getreg(register)
  -- do a regular paste
  vim.cmd("normal! p")
  -- and restore the contents of the active register
  vim.fn.setreg(register, contents)
end)

-- Move the selected lines up and down, but also, keep those lines
-- selected
--
-- These work, but throw an error when the lines are already at the
-- bounds of the file (at the start or the top). This needs to be fixed
map("x", ",", ":m '<-2<CR>gv=gv", { desc = "Move selected lines up" })
map("x", ".", ":m '>+1<CR>gv=gv", { desc = "Move selected lines down" })

-- Select all text in file using Ctrl+A
map("n", "<C-a>", "ggVG", { desc = "Select all text" })

-- Duplicate line (or selection) down
map("n", "<C-d>", '"ayy"ap', { desc = "Duplicate line down" })
map("x", "<C-d>", ":'<,'>t'><CR>gv", { desc = "Duplicate selection down" })

-- Exit terminal mode using Esc
--
-- Not needed in neovim, since apparently pressing Esc twice really fast
-- seems to get out of terminal mode
map("t", "<Esc>", [[<C-\><C-n>]], { desc = "Exit terminal mode to normal mode" })

--[[
The below function was generated by an LLM using the below prompt:

I want you to create a keymap for neovim <A-BS> (Alt + Backspace). it should delete the last word behind the cursor in insert mode. Let me give you some examples

When cursor is at the last letter of word e.g "some text|" then it should delete that word (but not the space behind it) e.g -> "some "

When cursor is in the middle of a word then it should delete it to the start of the word e.g "some tex|t" -> "some |t"

when cursor is *exactly* on the immediate whitespace (only single) after the word, it should delete to the start of the word e.g "some text |" -> "some |"

when cursor is past more than one whitespace of the word in a continous region of whitespaces, it should delete to the whitespaces following the end of previous word e.g "some text   |" -> "some text|"

make sure to handle single letter words the same way e.g "this is a|" -> "this is |"

in all of the examples above, make sure that after the deletion, the cursor ends up in the position shown in the examples

this deletion must preserve any buffer it uses. try to use some temporary register and even then preserve its contents at the end of this keybind

a "word" is defined as any continuous sequence of letters, numbers, and underscore

]]

-- Delete the previous "word" as defined by [0-9A-Za-z_]
--
-- *Behaviors*:
--   Delete word, keep the single space
--     "some text|" -> "some |"
--
--   Delete back to start of word
--     "some tex|t" -> "some |t"
--
--   Delete the word plus that one space in
--   case of single space after word
--     "some text |" -> "some |"
--
--   Delete all spaces, but not the word, when more than
--   one spaces are present after the word
--     "some text   | -> "some text|"
--
--   Correctly handle single letter words
--     "this is a|" -> "this is |"
--
-- Preserves registers (edits buffer directly). Stays in insert mode.

local function is_word_char(ch)
  return ch:match("^[0-9A-Za-z_]$") ~= nil
end

local function is_space_char(ch)
  return ch == " " or ch == "\t"
end

local function char_at(s, ci) -- ci: 0-based UTF-8 character index
  local b0 = vim.str_byteindex(s, ci)
  local b1 = vim.str_byteindex(s, ci + 1)
  return s:sub(b0 + 1, b1)
end

local function ctrl_bs_delete_prev_word()
  local win = 0
  local pos = vim.api.nvim_win_get_cursor(win) -- {row (1-based), col (0-based bytes)}
  local row = pos[1] - 1
  local col = pos[2]

  if col == 0 then
    return
  end

  local line = vim.api.nvim_get_current_line()
  local left = line:sub(1, col) -- bytes left of cursor
  local left_chars = vim.str_utfindex(left) -- char-count (UTF-8)

  local ci = left_chars -- cursor char index (right edge)
  local k = ci - 1 -- index of char immediately left of cursor

  -- Count contiguous spaces/tabs to the left
  local ws_run = 0
  while k >= 0 do
    local ch = char_at(left, k)
    if not is_space_char(ch) then
      break
    end
    ws_run = ws_run + 1
    k = k - 1
  end

  local start_char
  if ws_run >= 2 then
    -- Multiple spaces/tabs → delete them all
    start_char = ci - ws_run
  elseif ws_run == 1 then
    -- Exactly one space/tab
    if k >= 0 and is_word_char(char_at(left, k)) then
      -- Delete that one space + preceding word
      while k >= 0 and is_word_char(char_at(left, k)) do
        k = k - 1
      end
      start_char = k + 1
    else
      -- Just delete the single space/tab
      start_char = ci - 1
    end
  else
    -- No whitespace immediately to the left
    if k < 0 then
      return
    end
    if is_word_char(char_at(left, k)) then
      -- In or at end of a word → delete back to start of this word
      while k >= 0 and is_word_char(char_at(left, k)) do
        k = k - 1
      end
      start_char = k + 1
    else
      -- Non-word char → delete just that one char
      start_char = ci - 1
    end
  end

  -- Convert start_char (char index) to byte index within the full line
  local start_byte = vim.str_byteindex(left, start_char) -- 0-based
  local end_byte = col -- cursor byte index

  if start_byte < end_byte then
    -- Replace deleted region with nothing
    vim.api.nvim_buf_set_text(0, row, start_byte, row, end_byte, { "" })
    -- Place cursor at the new position (start of the deleted region)
    vim.api.nvim_win_set_cursor(win, { row + 1, start_byte })
  end
end

-- Due to some macos problems, my terminal kitty (and thus vim) is forced to receive the Ctrl+Backspace keystroke
-- as Alt-Backspace. Thus in vim, I have to bind this function to <A-BS>
vim.keymap.set("i", "<A-BS>", ctrl_bs_delete_prev_word, {
  silent = true,
  desc = "Ctrl-Backspace: delete previous word (custom)",
})
