# {{ Speed }}

repaint_delay 5
input_delay 1
sync_to_monitor no

# {{ Scrollback }}

scrollback_lines 3000

# only show scrollbar when view is scrolled up
scrollbar scrolled

scrollbar_width 1.0
scrollbar_hover_width 1.0
scrollbar_handle_opacity 0.9
scrollbar_radius 0.9
scrollbar_gap 1
scrollbar_min_handle_height 3
scrollbar_hitbox_expansion 0.1
scrollbar_track_opacity 0.25
scrollbar_track_hover_opacity 0.4
touch_scroll_multiplier 1.0

# {{ Misc }}

enable_audio_bell no

macos_quit_when_last_window_closed yes

# TODO: Change to socket + listen_on for better isolation
allow_remote_control yes
listen_on unix:/tmp/mykitty

allow_hyperlinks yes

# Enable everything execpt automatic setting of title.
# Title will be set via zsh shell instead because it offers
# greater customizability
shell_integration no-title

# quote-urls-at-prompt: If the text being pasted is a URL and the cursor is at a shell prompt,
#                       automatically quote the URL (needs shell_integration).
#
# confirm: Confirm the paste if the text to be pasted contains any terminal control codes
#          as this can be dangerous, leading to code execution if the shell/program running
#          in the terminal does not properly handle these.
paste_actions quote-urls-at-prompt,confirm
