# Start fresh
clear_all_shortcuts yes

# mouse_map right press ungrabbed mouse_select_command_output
# kitten hints

# Open new window
map ctrl+enter new_window
map ctrl+shift+enter new_window_with_cwd

# Open new tab
map ctrl+t new_tab
map ctrl+shift+t new_tab_with_cwd

# Move between tabs
map ctrl+[ previous_tab
map ctrl+] next_tab

map ctrl+shift+[ move_tab_backward
map ctrl+shift+] move_tab_forward

# Change Font Size
map ctrl+0 change_font_size all 0
map ctrl+equal  change_font_size all +2.0
map ctrl+minus  change_font_size all -2.0

# TODO: clean this copy/paste mess up
include keymaps-${KITTY_OS}.conf

# ----------------------------

# Keybinds with integration b/w kitty and neovim

# Move between windows
# map shift+left neighboring_window left
# map shift+right neighboring_window right
# map shift+up neighboring_window upm
# map shift+down neighboring_window down

# Using https://github.com/knubie/vim-kitty-navigator to integrate
# vim and kitty splits using the same shortcut key
map ctrl+j kitten pass_keys.py bottom ctrl+j
map ctrl+k kitten pass_keys.py top    ctrl+k
map ctrl+h kitten pass_keys.py left   ctrl+h
# FIXME: can no longer clear terminal
# map ctrl+l kitten pass_keys.py right  ctrl+l

# ----------------------------
# Keybinds to be disabled in neovim

# Update the current tab title
map --when-focus-on 'not var:in_neovim' ctrl+shift+i set_tab_title " "

# Close window
map --when-focus-on 'not var:in_neovim' ctrl+w close_window_with_confirmation ignore-shell

# Move to prev/next prompt in history
map --when-focus-on 'not var:in_neovim' ctrl+up scroll_to_prompt -1
map --when-focus-on 'not var:in_neovim' ctrl+down scroll_to_prompt 1

# Open last outputs in a pager
# TODO: Add the --stdin-add-formatting flag to launch command and add an ANSI escape code reader/colorizer to neovim
map --when-focus-on 'not var:in_neovim' ctrl+/ launch --stdin-source=@last_cmd_output --type=overlay nvim -R +'setlocal buftype=nofile bufhidden=wipe noswapfile nowrap' +'normal G'
map --when-focus-on 'not var:in_neovim' ctrl+shift+/ launch --stdin-source=@screen_scrollback --type=overlay nvim -R +'setlocal buftype=nofile bufhidden=wipe noswapfile nowrap' +'normal G'
