# Add blank line at the start of the prompt
add_newline = true

format = """
$username$hostname $git_branch$git_commit $python $fill$status
$directory $fill$cmd_duration
$character
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Timeout for commands executed by starship (in milliseconds)
command_timeout=1000

[fill]
symbol = ' '

[username]
style_user = 'bright-yellow'
format = '[$user]($style)'
show_always = true
aliases = { "qateef.ahmad" = "qateef" }

[hostname]
style = 'bold purple'
format = '[ @$hostname]($style)'
ssh_only = false
aliases = { "MT-H0Y07DWWNY-Qateef-Ahmad" = "motive" }

# TODO: use ssh_symbol
# ssh_symbol = '☁️'
# ssh_symbol = '🌏'
# format = '$hostname $ssh_symbol '

[directory]
# home_symbol = 'δ'
# home_symbol = '󱂵 '
home_symbol = ' '
# home_symbol = 'ζ'

truncation_length = 3
truncate_to_repo = false # Causes weird behavior when set to true
truncation_symbol = '⛬ '

# When non-zero, the directories that would be normally
# truncated are instead shown but only with this many number
# of starting characters. truncation_symbol is ignored in this
# case
# fish_style_pwd_dir_length = 0

# style of entire path
style="bold cyan"
# style of git repo folder (if any). Falls back to `style` if
# not defined
# repo_root_style="bold cyan"
# style of path before the git repo folder (if any).
# Falls back to `style` if not defined
# before_repo_root_style="bold cyan"

# $truncation_symbol is always prepended if there is some truncation
format = "[$path]($style)"

[directory.substitutions]
# TODO: this is very limited, and not according to my requirements
# rewrite this in rust as a custom starship module

[git_branch]
truncation_length = 15
truncation_symbol = '…'
# Disable it when in a detached head
only_attached = true

symbol = ''
style = 'bold red'

format = 'on [$symbol $branch]($style)'

[git_commit]
# Only show when in a detached head
only_detached = true
format = 'on [ [*](bold yellow) [$hash]($style underline)]($style)'
style = 'bold red'
commit_hash_length = 8

# I want it, but this module is too slow because
# `git status` itself is too slow on large repos
[git_status]
# pass

[kubernetes]
disabled = false
detect_files = ['k8s']

[python]
format = 'on [$symbol py:(${version} )(\($virtualenv\) )]($style)'
version_format = 'v${raw}'
# symbol = '🐍'
symbol = 'λ'
style = 'bold green'
# detect_extensions = ['py', 'ipynb']
# detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
detect_extensions = []
detect_files = []
detect_folders = []
python_binary = ["python", "python3", "python2"]

# Status of last command run
[status]
# Disabled by default. Need to enable it
disabled = false

symbol = 'Ӽ'
sigint_symbol = 'Ӽ'
signal_symbol = 'Ӽ'
not_found_symbol = '§'
# TODO: replace these once you find good symbols
# sigint_symbol = ''
# signal_symbol = 'Š'

# « »
# ⟪ ⟫
# ⟦ ⟧
# format = '[ « $symbol $common_meaning$signal_name$maybe_int » ]($style) '
format = ' [ $symbol $common_meaning$signal_name$maybe_int $symbol ]($style)'
style = 'bg:bright-red fg:black fg:bold'

# Try to figure out signal from exit code, if possible
recognize_signal_code = true

# Use the symbols defined above. Why is it not true by
# default ???
map_symbol = true

# Duration of last command run
[cmd_duration]
# ignore command that execute under this number of milliseconds
min_time = 7000
format = ' [⧗ $duration](bold yellow)'

# Actual Prompt
[character]
format = '[❯](bold blue) '

