# {{ Speed }}

repaint_delay 5
input_delay 1
sync_to_monitor no

# {{ Misc }}

enable_audio_bell no

macos_quit_when_last_window_closed yes

# TODO: Change to socket + listen_on for better isolation
allow_remote_control yes

allow_hyperlinks yes

# TODO: explore no-title option
shell_integration enabled