# =====================
# ======= Fonts =======
# =====================

include ./catppuccin-mocha.conf

font_family family="Fira Code"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.0

modify_font cell_width 95%

# ignored, controlled by shell_integration instead
# If we have it different than that of shell_integration, it slightly
# flashes to shape set by this setting before changing back to shape
# set by shell_integration. Therefore, it is a good idea to keep them
# matched
cursor_shape beam

background_opacity 0.95
# background_blur 20

# macos_titlebar_color background

macos_show_window_title_in window
macos_menubar_title_max_length 10

# ===========================================

# =======================
# ======= General =======
# =======================

enable_audio_bell no
macos_quit_when_last_window_closed yes

repaint_delay 5
input_delay 1
sync_to_monitor no

# TODO: Change to socket + listen_on for better isolation
allow_remote_control yes

allow_hyperlinks yes

# TODO: explore no-title option
shell_integration enabled

# =======================
# ======= Keymaps =======
# =======================

# Start fresh
clear_all_shortcuts yes


