include ./parts/general.conf
include ./parts/fonts.conf
include ./parts/appearance.conf
include ./parts/colors.conf
include ./parts/keymaps.conf

# Tab bar
# Key maps
# Sessions
# Awesome kittens
# Shell Prompt