# {{ OS Window }}
# mutally exclusive with background_opacity
# macos_titlebar_color background
macos_show_window_title_in window
macos_menubar_title_max_length 10

# {{ Terminal Surface }}
background_opacity 0.95
# background_blur 20

# {{ Cursor }}

# ignored, controlled by shell_integration instead
# If we have it different than that of shell_integration, it slightly
# flashes to shape set by this setting before changing back to shape
# set by shell_integration. Therefore, it is a good idea to keep them
# matched
cursor_shape beam

# {{ Tabs }}

tab_bar_style powerline
tab_powerline_style angled
tab_title_max_length 25
tab_title_template "{fmt.fg.tab}{index}:{title}"

# Todo: explore
# hide_window_decorations yes
