# Start fresh
clear_all_shortcuts yes

# mouse_map right press ungrabbed mouse_select_command_output
# kitten hints

enabled_layouts         grid,splits:split_axis=horizontal,stack,horizontal,vertical

# Open new window
map ctrl+enter new_window
map ctrl+shift+enter new_window_with_cwd

# Open new tab
map ctrl+t new_tab
map ctrl+shift+t new_tab_with_cwd

# Move between windows
map shift+left neighboring_window left
map shift+right neighboring_window right
map shift+up neighboring_window upm
map shift+down neighboring_window down

# Move between tabs
map ctrl+[ previous_tab
map ctrl+] next_tab

map ctrl+shift+[ move_tab_backward
map ctrl+shift+] move_tab_forward

# Close window
map ctrl+w close_window_with_confirmation ignore-shell

# Change Font Size
map ctrl+0 change_font_size all 0
map ctrl+equal  change_font_size all +2.0
map ctrl+minus  change_font_size all -2.0

# Move to prev/next prompt in history
# TODO: not working, fix
# map ctrl+up scroll_to_prompt -1
# map ctrl+down scroll_to_prompt 1

# Open last outputs in a pager
# TODO: enhance
map ctrl+/ launch --stdin-source=@last_cmd_output --stdin-add-formatting --type=overlay less +G -R
map ctrl+shift+/ launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay less +G -R

# Execptions
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
