"""Generate karabiner.json for my Mac keyboard layouts.

Goal: on macOS, make the bottom-left three modifier keys behave like Linux:
  #1 = cmd (acts as "linux ctrl"), #3/#4 = ctrl, #2 untouched.

Linux laptops and Galaxy65 in Linux mode are untouched (Karabiner is Mac-only).
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import json
from pathlib import Path

from keylib import (
    KeyboardDevice,
    Layout,
    build_karabiner_config,
    mappings,
    shell_mappings,
)


# ---------------------------------------------------------------------------
# Devices
# ---------------------------------------------------------------------------

builtin = KeyboardDevice.built_in(name="BL")
galaxy65 = KeyboardDevice.external(
    name="GX",
    idens=[
        (10473, 12645),  # Wired
        (10473, 8192),   # Bluetooth
    ],
)

# ---------------------------------------------------------------------------
# Physical -> intended modifier remaps, per keyboard.
#
# Bottom-left numbering (#1 is leftmost key on the bottom row):
#
# MacBook built-in physical: fn (#1) | ctrl (#2) | opt (#3) | cmd (#4)
#   fn  -> cmd     : #1 acts as linux-ctrl (save, etc.)
#   cmd -> ctrl    : #4 acts as mac-ctrl
#   #2 and #3 untouched
#
# Galaxy65 (Mac mode) physical: ctrl (#1) | opt (#2) | cmd (#3)
#   ctrl -> cmd    : #1 acts as linux-ctrl
#   cmd  -> ctrl   : #3 acts as mac-ctrl
#   #2 untouched
# ---------------------------------------------------------------------------

Layout(builtin,  {"fn":   "cmd", "cmd": "ctrl"}).register()
Layout(galaxy65, {"ctrl": "cmd", "cmd": "ctrl"}).register()

# ---------------------------------------------------------------------------
# App-specific overrides
# ---------------------------------------------------------------------------

# Chrome's devtools shortcut on macOS is cmd+opt+i. After the remaps above,
# pressing the linux-ctrl key + shift + i produces cmd+shift+i on both
# keyboards, so a single rule covers both devices.
mappings(
    desc="Chrome: devtools shortcut",
    apps=["com.google.Chrome"],
    maps=["cmd+shift+i == cmd+opt+i"],
)

# ---------------------------------------------------------------------------
# Global shell launchers
# ---------------------------------------------------------------------------

shell_mappings(
    desc="Shell launchers",
    maps=[
        ("opt+enter", "open -n -a /Applications/kitty.app"),
        ("opt+p",     "open -a Launchpad"),
    ],
)

# ---------------------------------------------------------------------------
# Emit karabiner.json
# ---------------------------------------------------------------------------

all_devices = [builtin, galaxy65]

output_path = Path(__file__).parent / "karabiner.json"
with output_path.open("w") as f:
    config = build_karabiner_config({
        "name": "Generated By genconfig.py",
        "selected": True,
        "devices": [
            {
                "ignore": False,
                "identifiers": {
                    "is_keyboard": True,
                    "is_pointing_device": True,
                    "vendor_id": vendor_id,
                    "product_id": product_id,
                },
            }
            for device in all_devices
            for (vendor_id, product_id) in device.idens
        ],
        "virtual_hid_keyboard": {"keyboard_type_v2": "ansi"},
    })
    json.dump(config, f, indent=2)

print(f"Output written to: {output_path}")
