return {}
-- return {
--   {
--     "xiyaowong/transparent.nvim",
--     lazy = false,
--     opts = {
--       extra_groups = {
--         -- seems to be working without these two below. will uncomment when needed
--         -- "NormalFloat", -- plugins which have float panel such as Lazy, Mason, LspInfo
--         -- "NvimTreeNormal" -- NvimTree
--       },
--     }
--   },
--   -- { "ellisonleao/gruvbox.nvim" },
--   { "catppuccin/nvim", name = "catppuccin", priority = 1000 },

--   -- Configure LazyVim to load gruvbox
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "catppuccin-mocha",
--     },
--   },
-- }