# {{ OS Window }}
macos_show_window_title_in window
macos_menubar_title_max_length 10

# makes the titlebar same color as terminal surface
# mutally exclusive with background_opacity
# macos_titlebar_color background

# Remove title bar
hide_window_decorations yes

# {{ Terminal Surface }}

background_opacity 0.95
# background_blur 20

# When the OS window size is not an exact multiple of the cell size, the
# cell area of the terminal window will have some extra padding on
# the sides. You can control how that padding is distributed with this option
placement_strategy top-left

# Draw only the borders (splits) that separate the
# panes from a neighbor one
draw_minimal_borders yes

# Width of these borders
window_border_width 0.5pt

# Padding of Panes: <vertical> <horizontal>
window_padding_width 0 12

# {{ Cursor }}

# ignored, controlled by shell_integration instead
# If we have it different than that of shell_integration, it slightly
# flashes to shape set by this setting before changing back to shape
# set by shell_integration. Therefore, it is a good idea to keep them
# matched
cursor_shape beam

# {{ Tabs }}

tab_bar_style powerline
tab_powerline_style angled
tab_title_max_length 25
tab_title_template "{fmt.fg.tab}{index}:{title}"

# {{ Layout }}

enabled_layouts grid,splits:split_axis=horizontal,stack,horizontal,vertical
