# {{ Font Family }}


# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontMono-Retina.ttf: FiraCode Nerd Font Mono,FiraCode Nerd Font Mono Ret:style=Retina,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontPropo-Bold.ttf: FiraCode Nerd Font Propo:style=Bold
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFont-Regular.ttf: FiraCode Nerd Font:style=Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontMono-Regular.ttf: FiraCode Nerd Font Mono:style=Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFont-SemiBold.ttf: FiraCode Nerd Font,FiraCode Nerd Font SemBd:style=SemiBold,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontPropo-Light.ttf: FiraCode Nerd Font Propo,FiraCode Nerd Font Propo Light:style=Light,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontPropo-Medium.ttf: FiraCode Nerd Font Propo,FiraCode Nerd Font Propo Med:style=Medium,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFont-Bold.ttf: FiraCode Nerd Font:style=Bold
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontPropo-Regular.ttf: FiraCode Nerd Font Propo:style=Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontMono-Light.ttf: FiraCode Nerd Font Mono,FiraCode Nerd Font Mono Light:style=Light,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontPropo-SemiBold.ttf: FiraCode Nerd Font Propo,FiraCode Nerd Font Propo SemBd:style=SemiBold,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontMono-Medium.ttf: FiraCode Nerd Font Mono,FiraCode Nerd Font Mono Med:style=Medium,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontMono-Bold.ttf: FiraCode Nerd Font Mono:style=Bold
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontPropo-Retina.ttf: FiraCode Nerd Font Propo,FiraCode Nerd Font Propo Ret:style=Retina,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFont-Retina.ttf: FiraCode Nerd Font,FiraCode Nerd Font Ret:style=Retina,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFont-Medium.ttf: FiraCode Nerd Font,FiraCode Nerd Font Med:style=Medium,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFont-Light.ttf: FiraCode Nerd Font,FiraCode Nerd Font Light:style=Light,Regular
# /Users/qateef.ahmad/Library/Fonts/FiraCodeNerdFontMono-SemiBold.ttf: FiraCode Nerd Font Mono,FiraCode Nerd Font Mono SemBd:style=SemiBold,Regular

font_family family="Fira Code"
# font_family family="Maple Mono"
bold_font auto
italic_font auto
bold_italic_font auto

# {{ Font Size }}

font_size 14.0
# font_size 15.0

# {{ Misc }}

modify_font cell_width 95%

# https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 FiraCode Nerd Font
