import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import json
from pathlib import Path
from keylib import (
    mappings,
    global_shell_mappings,
    KeyboardDevice,
    build_karabiner_config,
    KeySet,
    tp
)

# =====================================
# ============= Keyboards =============
# =====================================

builtin = KeyboardDevice.built_in(name="BL")
galaxy65 = KeyboardDevice.external(
    name="GX",
    idens=[
        (10473, 12645), # Wired mode
        (10473, 8192),  # Bluetooth mode
    ]
)

all_devices = [builtin, galaxy65]

# ====================================
# =========== Applications ===========
# ====================================

chrome = "com.google.Chrome"
terminals = ["net.kovidgoyal.kitty", "com.apple.Terminal"]
# finder = "com.apple.finder"

# ===========================================
# ============= Global Keymaps ==============
# ===========================================

global_shell_mappings(
    desc="Common Shell Mapping",
    maps=[
        ("opt+enter", "sh -c '/Applications/kitty.app/Contents/MacOS/kitty --single-instance --directory=/Users/qateef.ahmad --detach'"),
        ("opt+p", "open -a Launchpad"),
    ]
)

# ====================================
# ============= Keymaps ==============
# ====================================

mappings(
    desc="Chrome: Force Keymaps",
    devices=[builtin],
    apps=[chrome],
    maps=[
        "fn+shift+i == cmd+opt+i",
    ]
)

mappings(
    desc="Chrome: Force Keymaps",
    devices=[galaxy65],
    apps=[chrome],
    maps=[
        "cmd+shift+i == cmd+opt+i",
    ]
)

# -----------------------------------------

mappings(
    desc="Terminal: Special Copy and Paste actions",
    devices=[builtin],
    apps=terminals,
    maps=tp("fn+shift", "cmd", ['c', 'v'])
)

mappings(
    desc="Terminal: Special Copy and Paste actions",
    devices=[galaxy65],
    apps=terminals,
    maps=tp("cmd+shift", "cmd", ['c', 'v'])
)

# -----------------------------------------

mappings(
    desc="Terminal: <fn> + <shift> to <ctrl> + <shift>",
    devices=[builtin],
    apps=terminals,
    maps=tp("fn+shift", "ctrl+shift", [
        KeySet.special - {"delete"},
        KeySet.printable - {'c', 'v'},
        KeySet.v_arrows,
    ])
)

mappings(
    desc="Terminal: <cmd> + <shift> to <ctrl> + <shift>",
    devices=[galaxy65],
    apps=terminals,
    maps=tp("cmd+shift", "ctrl+shift", [
        KeySet.special - {"delete"},
        KeySet.printable - {'c', 'v'},
        KeySet.v_arrows,
    ])
)

# -----------------------------------------

mappings(
    desc="Terminal: <fn> to <ctrl>",
    devices=[builtin],
    apps=terminals,
    maps=tp("fn", "ctrl", [
        KeySet.special - {"delete"},
        KeySet.printable,
        KeySet.v_arrows,
    ]),
)

mappings(
    desc="Terminal: <cmd> to <ctrl>",
    devices=[galaxy65],
    apps=terminals,
    maps=tp("cmd", "ctrl", [
        KeySet.special - {"delete"},
        KeySet.printable,
        KeySet.v_arrows,
    ]),
)

# -----------------------------------------

mappings(
    desc="(Deprecate) Global: Cursor Movement By Word",
    devices=[builtin],
    maps=[
        *tp("fn", "opt", ["delete"]),
        *tp("fn", "opt", KeySet.h_arrows),
        *tp("fn+shift", "opt+shift", KeySet.h_arrows),
    ]
)

mappings(
    desc="(Deprecate) Global: Cursor Movement By Word",
    devices=[galaxy65],
    maps=[
        *tp("cmd", "opt", ["delete"]),
        *tp("cmd", "opt", KeySet.h_arrows),
        *tp("cmd+shift", "opt+shift", KeySet.h_arrows),
    ]
)

# -----------------------------------------

mappings(
    desc="Global: <fn> + <opt> to <cmd> + <opt> (because macos cmd = app's ctrl)",
    devices=[builtin],
    maps=tp("fn+opt", "cmd+opt", [
        KeySet.arrows,
        KeySet.special,
        KeySet.printable,
    ])
)

# -----------------------------------------

mappings(
    desc="Global: <fn> + <shift> to <cmd> + <shift> (because macos cmd = app's ctrl)",
    devices=[builtin],
    maps=tp("fn+shift", "cmd+shift", [
        KeySet.special - {"delete"},
        # Cannot bind horizontal arrows due cursor movement mappings
        # TODO: look into thid
        KeySet.v_arrows,
        KeySet.printable,
    ]),
)

# -----------------------------------------

mappings(
    desc="Global: <fn> to <cmd> (because macos cmd = app's ctrl)",
    devices=[builtin],
    maps=tp("fn", "cmd", [
        KeySet.special - {"delete"},
        KeySet.printable,
    ])
)

# ====================================
# ============= Generate =============
# ====================================

output_path = Path(__file__).parent / "karabiner.json"
with output_path.open("w") as f:
    config = build_karabiner_config({
        "name": "Generated By genconfig.py",
        "selected": True,
        "devices": [
            {
                "ignore": False,
                "identifiers": {
                    "is_keyboard": True,
                    "is_pointing_device": True,
                    "vendor_id": vendor_id,
                    "product_id": product_id,
                }
            }
            for device in all_devices
            for (vendor_id, product_id) in device.idens
        ],
        "virtual_hid_keyboard": {
            "keyboard_type_v2": "ansi"
        }
    })

    json.dump(config, f, indent=2)

print(f"Output written to: {output_path}")
