include ./parts/general.conf
include ./parts/fonts.conf
include ./parts/appearance.conf
include ./parts/colors.conf
include ./parts/keymaps.conf

# shell zsh --interactive

# Sessions
# Awesome kittens
